version: '3.1'
services:
  mysql:
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:  # Use root/example as user/password
      MYSQL_ROOT_PASSWORD: example

  
  tastebudsdelightback:
    image: "node:12"
    # restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=docker-dev
    volumes:
      - ./:/home/node/app
    ports:
      - 8000:8000
    depends_on:
      - mysql
    # command: ["./wait-for-it.sh","mysql:3306","--","npm","start"]
    command: ["npm", "start"]
    

  
  imagestorage:
    image: "node:12"
    # restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=docker-dev
      - SQL_HOST=mysql
      - SQL_USER=root
      - SQL_PASSWORD=example
      - SQL_DATABASE=tastbuds
    volumes:
      - ../imagestorage/:/home/node/app
    ports:
      - 8010:8010
    # command: ["./wait-for-it.sh","mysql:3306","--","npm","start"]
    command: ["npm", "start"]


  adminer:
    image: adminer
    restart: always
    ports:
      - 8020:8080

